#Places
## Get places list
GET http://localhost:4000/places HTTP/1.1
Content-Type: application/json

###

## Add new place
POST http://localhost:4000/places HTTP/1.1
Content-Type: application/json

{
  "title": "The Joshua Tree House",
  "description": "LovBLABLABLABLAourhood, lot of trendy shops, restaurants and bars in a walking distance.;The house is very good, very happy, hygienic and simple living conditions around it are also very good.",
  "postDate":"2024-05-14T21:23:48.979Z",
  "city": "Cologne",
  "previewImage": "house-02.jpg",
  "images": [
    "house-05.jpg",
    "house-11.jpg",
    "room-16.jpg",
    "apartment-19.jpg",
    "apartment-1.jpg",
    "apartment-9.jpg"
  ],
  "isPremium": false,
  "typePlace": "Apartment",
  "bedrooms": 7,
  "guests": 4,
  "price": 77777,
  "benefits": [
    "Washer"
  ],
  "userId": "664d1102a83e76469bdbe1a2",
  "latitude": 50.938361,
  "longitude": 6.959974
}

###

## Get place by placeId
GET http://localhost:4000/places/664d1102a83e76469bdbe1a9 HTTP/1.1

###

## Patch place by placeId
PATCH http://localhost:4000/places/664d1102a83e76469bdbe36d HTTP/1.1
Content-Type: application/json

{
  "bedrooms": 4,
  "guests": 2
}
###

## Delete place by placeId
DELETE http://localhost:4000/places/664d1102a83e76469bdbe1a9 HTTP/1.1

###

## Get premium places by City
GET http://localhost:4000/places/premium/amsterdam HTTP/1.1

###

## Get all reviews to the place by placeId
GET http://localhost:4000/places/664d1102a83e76469bdbe1a4/reviews HTTP/1.1

###

## Get all favorites by userId from token
GET http://localhost:4000/places/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NvaWRAbGtsbGQuY29tIiwibmFtZSI6Iktla3MiLCJpc1BybyI6ZmFsc2UsImlkIjoiNjY2ZGNiNWJlNGY5OGZhY2Q0M2EwYjcxIiwiaWF0IjoxNzE4NDczODMyLCJleHAiOjE3MTg2NDY2MzJ9._txN6KpBTONTWeS2C8BHergy4KnvJIYoTm8pMeXvw4o

###

## Change isFavorite status by placeId
PATCH http://localhost:4000/places/664d1102a83e76469bdbe1a9/favorites/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NvaWRAbGtsbGQuY29tIiwibmFtZSI6Iktla3MiLCJpc1BybyI6ZmFsc2UsImlkIjoiNjY2ZGNiNWJlNGY5OGZhY2Q0M2EwYjcxIiwiaWF0IjoxNzE4NDczODMyLCJleHAiOjE3MTg2NDY2MzJ9._txN6KpBTONTWeS2C8BHergy4KnvJIYoTm8pMeXvw4o

###
