#Places
## Get places list
GET http://localhost:4000/places HTTP/1.1
Content-Type: application/json

###

## Add new place
POST http://localhost:4000/places HTTP/1.1
Content-Type: application/json

{
  "title": "The Joshua Tree House",
  "description": "LovBLABLABLABLAourhood, lot of trendy shops, restaurants and bars in a walking distance.;The house is very good, very happy, hygienic and simple living conditions around it are also very good.",
  "city": "Cologne",
  "previewImage": "house-02.jpg",
  "images": [
    "house-05.jpg",
    "house-11.jpg",
    "room-16.jpg",
    "apartment-19.jpg",
    "apartment-1.jpg",
    "apartment-9.jpg"
  ],
  "isPremium": false,
  "isFavorite": false,
  "rating": 1.6,
  "typePlace": "Apartment",
  "bedrooms": 7,
  "guests": 4,
  "price": 77777,
  "benefits": [
    "Washer"
  ],
  "latitude": 50.938361,
  "longitude": 6.959974
}

###
