# Reviews
## Create new review

POST http://localhost:4000/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3Nzc29mYXZAbGtsbGQuY29tIiwibmFtZSI6Iktla2RzIiwiaXNQcm8iOmZhbHNlLCJpZCI6IjY2NzA0MDA2NWZjZjJlMDgzMjI3MjE5YSIsImlhdCI6MTcxODcxNzk1MSwiZXhwIjoxNzE4ODkwNzUxfQ.jMEvEB31CTtMggt8POsWP-b91nEdMe_ByJkeGVIePRA
{
  "placeId": "664d1102a83e76469bdbe1a4",
  "postFate": "2024-06-11T16:24:18.315Z",
  "text": "в от кексофва, после похода по горам) крутой вид из окон",
  "rating": 2
}

###
